---
name: "test"
on:
  push:
    branches:
    - "**"
  pull_request:

jobs:
  publish:
    name: "test"
    runs-on: "ubuntu-22.04"

    steps:
    - name: "checkout code"
      uses: "actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b" # v3.0.2

    - name: "setup pnpm"
      uses: "pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd" # 2.2.1

    - name: "setup node"
      uses: "actions/setup-node@56337c425554a6be30cdef71bf441f15be286854" # v3.1.1
      with:
        node-version: "16.15.0"
        cache: "pnpm"

    - name: "install dependencies"
      run: "pnpm i"

    - name: "test"
      run: "pnpm run test"

    - name: "upload test coverage"
      run: |
        curl -O https://uploader.codecov.io/latest/linux/codecov

        # gpg integrity check
        echo ${{ secrets.CODECOV_PUB_KEY }} | gpg --no-default-keyring --keyring keys.gpg --import
        curl -S https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
        curl -S https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
        gpgv codecov.SHA256SUM.sig codecov.SHA256SUM

        chmod +x codecov
        ./codecov
